import tkinter as tk
from tkinter import *
root = tk.Tk()
root.geometry("2000x1000")
root.title("ChatRooms")
greetingLabel=tk.Label(root, text="Greetings User!", font=('arial', 50))
greetingLabel.grid(row=1, column=2)
chatLabel=tk.Label(root, text="Chat", font=('arial', 100)).grid(row=4, column=3)
roomsLabel=tk.Label(root, text="Rooms", font=('arial', 50)).grid(row=4, column=4)
def buttonclick():
    greetingLabel.config(text="Button clicked!")
greetingbutton=tk.Button(root, text="Click Me!", font=('arial', 20), command=buttonclick).grid(row=8, column=4)
textbox=tk.Text(root, font=('arial', 2)).grid(row=6, column=4)
buttonframe=tk.Frame(root)
buttonframe.grid(row=9, column=2)
btn1=tk.Button(buttonframe, text="1", font=('Arial', 50)).grid(row=9, column=0)
btn2=tk.Button(buttonframe, text="2", font=('Arial', 50)).grid(row=9, column=3)
btn3=tk.Button(buttonframe, text="3", font=('Arial', 50)).grid(row=9, column=6)
frame=tk.Frame(root)
frame.grid(row=10, column=20)
greetingentry=tk.Entry(frame)
greetingentry.grid(row=11, column=20)
textlist=tk.Listbox(frame)
textlist.grid(row=11, column=21)
root.mainloop()